### PR TITLE
Connected FlipsideViewController IBOutlets

### PR DESCRIPTION
**Pull request by rg5d**
Connected FlipsideViewController IBOutlets and some other nits

### CODE REVIEW

**Comment by rg5d** [comment]
Hey Chris I made some progress on MainViewController imagePickerDelegate. Check the constnats and see if they still make sense. Also, look at flagHeight. In your ObjC code you only set this in testButton method.

**Comment by CPLamb** [comment]
Whoops, I didn't see this request, buried in the email chain.  Disregard prior email.

**Comment by CPLamb** [comment]
I'll do that although I need to do apt clean this morning.
I noticed in GitHub, that you haven't merge requested your latest stuff?
Cheers,CPL

```
 On Thursday, October 8, 2015 12:58 AM, rg5d <notifications@github.com> wrote:
```

 Hey Chris I made some progress on MainViewController imagePickerDelegate. Check the constnats and see if they still make sense. Also, look at flagHeight. In your ObjC code you only set this in testButton method.—

**Comment by CPLamb** [comment]
OK,I merged your stuff, pulled it down from origin/master, N I see all your changes.  Way cool!  I think we have the basic GitHub down.
Now as to code;   
- I think your getting a good handle on it from your comments
- At this point originally, I worked out a lot of the constants, empirically with extensive testing & calcing.
- I would just hardcode the distantObject height (flag = 4 ft, switchplate = 6 inches, whatever) and work thru it.   
- You could find a few different switchplates (or door heights) around you apt. and measure the distances to them.  That's how I got it together.
- I can certainly help with that, now that we can pass code back N forth.
- Nice going!
  As to maintaining the code & minimizing possible merge issues, I think that we should stay in each other's files for the moment, and I'm probably going to try N commit & merge request at the end of each of my programming sessions.
  Anyway, cheers, and call me if you like I'll be around,CPL
  
   On Thursday, October 8, 2015 12:58 AM, rg5d notifications@github.com wrote:
  
  Hey Chris I made some progress on MainViewController imagePickerDelegate. Check the constnats and see if they still make sense. Also, look at flagHeight. In your ObjC code you only set this in testButton method.—

**Pull request merged**
